# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectDialog(object):
    def setupUi(self, ProjectDialog):
        ProjectDialog.setObjectName("ProjectDialog")
        ProjectDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ProjectDialog.resize(350, 220)
        ProjectDialog.setMinimumSize(QtCore.QSize(320, 220))
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.datastoreBox = QtWidgets.QGroupBox(ProjectDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.datastoreBox.setFont(font)
        self.datastoreBox.setObjectName("datastoreBox")
        self.gridLayout = QtWidgets.QGridLayout(self.datastoreBox)
        self.gridLayout.setObjectName("gridLayout")
        self.dataTypeCombo = QtWidgets.QComboBox(self.datastoreBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTypeCombo.sizePolicy().hasHeightForWidth())
        self.dataTypeCombo.setSizePolicy(sizePolicy)
        self.dataTypeCombo.setObjectName("dataTypeCombo")
        self.dataTypeCombo.addItem("")
        self.dataTypeCombo.addItem("")
        self.gridLayout.addWidget(self.dataTypeCombo, 0, 1, 1, 2)
        self.dataNewButton = QtWidgets.QPushButton(self.datastoreBox)
        self.dataNewButton.setObjectName("dataNewButton")
        self.gridLayout.addWidget(self.dataNewButton, 5, 1, 1, 1)
        self.dataOpenButton = QtWidgets.QPushButton(self.datastoreBox)
        self.dataOpenButton.setObjectName("dataOpenButton")
        self.gridLayout.addWidget(self.dataOpenButton, 5, 2, 1, 1)
        self.dataTypeLabel = QtWidgets.QLabel(self.datastoreBox)
        self.dataTypeLabel.setObjectName("dataTypeLabel")
        self.gridLayout.addWidget(self.dataTypeLabel, 0, 0, 1, 1)
        self.dataSelectLabel = QtWidgets.QLabel(self.datastoreBox)
        self.dataSelectLabel.setObjectName("dataSelectLabel")
        self.gridLayout.addWidget(self.dataSelectLabel, 1, 0, 1, 1)
        self.dataSelectCombo = QtWidgets.QComboBox(self.datastoreBox)
        self.dataSelectCombo.setObjectName("dataSelectCombo")
        self.gridLayout.addWidget(self.dataSelectCombo, 1, 1, 1, 2)
        self.schemaLabel = QtWidgets.QLabel(self.datastoreBox)
        self.schemaLabel.setObjectName("schemaLabel")
        self.gridLayout.addWidget(self.schemaLabel, 3, 0, 1, 1)
        self.schemaCombo = QtWidgets.QComboBox(self.datastoreBox)
        self.schemaCombo.setObjectName("schemaCombo")
        self.gridLayout.addWidget(self.schemaCombo, 3, 1, 1, 2)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 3)
        self.verticalLayout.addWidget(self.datastoreBox)
        self.closeButtonBox = QtWidgets.QDialogButtonBox(ProjectDialog)
        self.closeButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.closeButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.closeButtonBox.setObjectName("closeButtonBox")
        self.verticalLayout.addWidget(self.closeButtonBox)

        self.retranslateUi(ProjectDialog)
        self.closeButtonBox.accepted.connect(ProjectDialog.accept)
        self.closeButtonBox.rejected.connect(ProjectDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProjectDialog)

    def retranslateUi(self, ProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectDialog.setWindowTitle(_translate("ProjectDialog", "Project Settings"))
        self.datastoreBox.setTitle(_translate("ProjectDialog", "Project data store"))
        self.dataTypeCombo.setItemText(0, _translate("ProjectDialog", "Personal geodatabase"))
        self.dataTypeCombo.setItemText(1, _translate("ProjectDialog", "Shape files folder"))
        self.dataNewButton.setText(_translate("ProjectDialog", "New..."))
        self.dataOpenButton.setText(_translate("ProjectDialog", "Open..."))
        self.dataTypeLabel.setText(_translate("ProjectDialog", "Type"))
        self.dataSelectLabel.setText(_translate("ProjectDialog", "Select"))
        self.schemaLabel.setText(_translate("ProjectDialog", "Schema"))
