# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SettingsDialog.resize(320, 375)
        SettingsDialog.setMinimumSize(QtCore.QSize(320, 230))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingsTab = QtWidgets.QTabWidget(SettingsDialog)
        self.settingsTab.setEnabled(True)
        self.settingsTab.setObjectName("settingsTab")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.formLayout = QtWidgets.QFormLayout(self.analysisTab)
        self.formLayout.setObjectName("formLayout")
        self.engineHostLabel = QtWidgets.QLabel(self.analysisTab)
        self.engineHostLabel.setObjectName("engineHostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.engineHostLabel)
        self.engineHostEdit = QtWidgets.QLineEdit(self.analysisTab)
        self.engineHostEdit.setObjectName("engineHostEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.engineHostEdit)
        self.engineTestButton = QtWidgets.QPushButton(self.analysisTab)
        self.engineTestButton.setObjectName("engineTestButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.engineTestButton)
        self.engineTestText = QtWidgets.QLineEdit(self.analysisTab)
        self.engineTestText.setEnabled(True)
        self.engineTestText.setFrame(False)
        self.engineTestText.setReadOnly(True)
        self.engineTestText.setObjectName("engineTestText")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.engineTestText)
        self.settingsTab.addTab(self.analysisTab, "")
        self.explorerTab = QtWidgets.QWidget()
        self.explorerTab.setObjectName("explorerTab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.explorerTab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.colourCombo = QtWidgets.QComboBox(self.explorerTab)
        self.colourCombo.setObjectName("colourCombo")
        self.colourCombo.addItem("")
        self.colourCombo.addItem("")
        self.colourCombo.addItem("")
        self.colourCombo.addItem("")
        self.colourCombo.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.colourCombo)
        self.colourLabel = QtWidgets.QLabel(self.explorerTab)
        self.colourLabel.setObjectName("colourLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.colourLabel)
        self.settingsTab.addTab(self.explorerTab, "")
        self.verticalLayout_2.addWidget(self.settingsTab)
        self.closeButtonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.closeButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.closeButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.closeButtonBox.setObjectName("closeButtonBox")
        self.verticalLayout_2.addWidget(self.closeButtonBox)

        self.retranslateUi(SettingsDialog)
        self.settingsTab.setCurrentIndex(1)
        self.closeButtonBox.accepted.connect(SettingsDialog.accept)
        self.closeButtonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Space Synatx Toolkit Settings"))
        self.engineHostLabel.setText(_translate("SettingsDialog", "depthmapXnet IP"))
        self.engineHostEdit.setText(_translate("SettingsDialog", "localhost"))
        self.engineTestButton.setText(_translate("SettingsDialog", "Test"))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.analysisTab), _translate("SettingsDialog", "Graph Analysis"))
        self.colourCombo.setItemText(0, _translate("SettingsDialog", "Classic"))
        self.colourCombo.setItemText(1, _translate("SettingsDialog", "Red - blue"))
        self.colourCombo.setItemText(2, _translate("SettingsDialog", "Greyscale"))
        self.colourCombo.setItemText(3, _translate("SettingsDialog", "Monochrome"))
        self.colourCombo.setItemText(4, _translate("SettingsDialog", "Classic inflection"))
        self.colourLabel.setText(_translate("SettingsDialog", "Default colour range:"))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.explorerTab), _translate("SettingsDialog", "Explorer"))
