# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_DepthmapAdvanced.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DepthmapAdvancedDialog(object):
    def setupUi(self, DepthmapAdvancedDialog):
        DepthmapAdvancedDialog.setObjectName("DepthmapAdvancedDialog")
        DepthmapAdvancedDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        DepthmapAdvancedDialog.resize(280, 230)
        DepthmapAdvancedDialog.setMinimumSize(QtCore.QSize(280, 230))
        self.gridLayout = QtWidgets.QGridLayout(DepthmapAdvancedDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.axialCalculateChoiceCheck = QtWidgets.QCheckBox(DepthmapAdvancedDialog)
        self.axialCalculateChoiceCheck.setObjectName("axialCalculateChoiceCheck")
        self.gridLayout.addWidget(self.axialCalculateChoiceCheck, 1, 0, 1, 2)
        self.axialDistanceCombo = QtWidgets.QComboBox(DepthmapAdvancedDialog)
        self.axialDistanceCombo.setObjectName("axialDistanceCombo")
        self.axialDistanceCombo.addItem("")
        self.axialDistanceCombo.addItem("")
        self.axialDistanceCombo.addItem("")
        self.gridLayout.addWidget(self.axialDistanceCombo, 3, 1, 1, 1)
        self.axialCalculateFullCheck = QtWidgets.QCheckBox(DepthmapAdvancedDialog)
        self.axialCalculateFullCheck.setObjectName("axialCalculateFullCheck")
        self.gridLayout.addWidget(self.axialCalculateFullCheck, 0, 0, 1, 2)
        self.closeButtonBox = QtWidgets.QDialogButtonBox(DepthmapAdvancedDialog)
        self.closeButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.closeButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.closeButtonBox.setObjectName("closeButtonBox")
        self.gridLayout.addWidget(self.closeButtonBox, 6, 0, 1, 2)
        self.axialCalculateNormCheck = QtWidgets.QCheckBox(DepthmapAdvancedDialog)
        self.axialCalculateNormCheck.setObjectName("axialCalculateNormCheck")
        self.gridLayout.addWidget(self.axialCalculateNormCheck, 2, 0, 1, 2)
        self.axialDistanceLabel = QtWidgets.QLabel(DepthmapAdvancedDialog)
        self.axialDistanceLabel.setObjectName("axialDistanceLabel")
        self.gridLayout.addWidget(self.axialDistanceLabel, 3, 0, 1, 1)
        self.axialRadiusCombo = QtWidgets.QComboBox(DepthmapAdvancedDialog)
        self.axialRadiusCombo.setObjectName("axialRadiusCombo")
        self.axialRadiusCombo.addItem("")
        self.axialRadiusCombo.addItem("")
        self.axialRadiusCombo.addItem("")
        self.gridLayout.addWidget(self.axialRadiusCombo, 4, 1, 1, 1)
        self.axialRadiusLabel = QtWidgets.QLabel(DepthmapAdvancedDialog)
        self.axialRadiusLabel.setObjectName("axialRadiusLabel")
        self.gridLayout.addWidget(self.axialRadiusLabel, 4, 0, 1, 1)
        self.axialStubsLabel = QtWidgets.QLabel(DepthmapAdvancedDialog)
        self.axialStubsLabel.setObjectName("axialStubsLabel")
        self.gridLayout.addWidget(self.axialStubsLabel, 5, 0, 1, 1)
        self.axialStubsEdit = QtWidgets.QLineEdit(DepthmapAdvancedDialog)
        self.axialStubsEdit.setPlaceholderText("")
        self.axialStubsEdit.setObjectName("axialStubsEdit")
        self.gridLayout.addWidget(self.axialStubsEdit, 5, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(DepthmapAdvancedDialog)
        self.closeButtonBox.accepted.connect(DepthmapAdvancedDialog.accept)
        self.closeButtonBox.rejected.connect(DepthmapAdvancedDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DepthmapAdvancedDialog)

    def retranslateUi(self, DepthmapAdvancedDialog):
        _translate = QtCore.QCoreApplication.translate
        DepthmapAdvancedDialog.setWindowTitle(_translate("DepthmapAdvancedDialog", "Advanced Settings"))
        self.axialCalculateChoiceCheck.setText(_translate("DepthmapAdvancedDialog", "Calculate choice"))
        self.axialDistanceCombo.setItemText(0, _translate("DepthmapAdvancedDialog", "Topological"))
        self.axialDistanceCombo.setItemText(1, _translate("DepthmapAdvancedDialog", "Angular"))
        self.axialDistanceCombo.setItemText(2, _translate("DepthmapAdvancedDialog", "Metric"))
        self.axialCalculateFullCheck.setText(_translate("DepthmapAdvancedDialog", "Calculate full set of measures"))
        self.axialCalculateNormCheck.setText(_translate("DepthmapAdvancedDialog", "Calculate NACH and NAIN"))
        self.axialDistanceLabel.setText(_translate("DepthmapAdvancedDialog", "Distance type:"))
        self.axialRadiusCombo.setItemText(0, _translate("DepthmapAdvancedDialog", "Topological"))
        self.axialRadiusCombo.setItemText(1, _translate("DepthmapAdvancedDialog", "Angular"))
        self.axialRadiusCombo.setItemText(2, _translate("DepthmapAdvancedDialog", "Metric"))
        self.axialRadiusLabel.setText(_translate("DepthmapAdvancedDialog", "Radius type:"))
        self.axialStubsLabel.setText(_translate("DepthmapAdvancedDialog", "Stubs removal %:"))
