# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_VerificationSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VerificationSettingsDialog(object):
    def setupUi(self, VerificationSettingsDialog):
        VerificationSettingsDialog.setObjectName("VerificationSettingsDialog")
        VerificationSettingsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        VerificationSettingsDialog.resize(320, 180)
        VerificationSettingsDialog.setMinimumSize(QtCore.QSize(320, 180))
        self.gridLayout = QtWidgets.QGridLayout(VerificationSettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.axialThresholdLabel = QtWidgets.QLabel(VerificationSettingsDialog)
        self.axialThresholdLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.axialThresholdLabel.setObjectName("axialThresholdLabel")
        self.gridLayout.addWidget(self.axialThresholdLabel, 0, 0, 1, 1)
        self.axialThresholdEdit = QtWidgets.QLineEdit(VerificationSettingsDialog)
        self.axialThresholdEdit.setObjectName("axialThresholdEdit")
        self.gridLayout.addWidget(self.axialThresholdEdit, 0, 1, 1, 1)
        self.axialMinimumLabel = QtWidgets.QLabel(VerificationSettingsDialog)
        self.axialMinimumLabel.setObjectName("axialMinimumLabel")
        self.gridLayout.addWidget(self.axialMinimumLabel, 1, 0, 1, 1)
        self.axialMinimumEdit = QtWidgets.QLineEdit(VerificationSettingsDialog)
        self.axialMinimumEdit.setObjectName("axialMinimumEdit")
        self.gridLayout.addWidget(self.axialMinimumEdit, 1, 1, 1, 1)
        self.unlinksThresholdLabel = QtWidgets.QLabel(VerificationSettingsDialog)
        self.unlinksThresholdLabel.setObjectName("unlinksThresholdLabel")
        self.gridLayout.addWidget(self.unlinksThresholdLabel, 2, 0, 1, 1)
        self.unlinksThresholdEdit = QtWidgets.QLineEdit(VerificationSettingsDialog)
        self.unlinksThresholdEdit.setObjectName("unlinksThresholdEdit")
        self.gridLayout.addWidget(self.unlinksThresholdEdit, 2, 1, 1, 1)
        self.linksThresholdEdit = QtWidgets.QLineEdit(VerificationSettingsDialog)
        self.linksThresholdEdit.setObjectName("linksThresholdEdit")
        self.gridLayout.addWidget(self.linksThresholdEdit, 3, 1, 1, 1)
        self.closeButtonBox = QtWidgets.QDialogButtonBox(VerificationSettingsDialog)
        self.closeButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.closeButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.closeButtonBox.setObjectName("closeButtonBox")
        self.gridLayout.addWidget(self.closeButtonBox, 4, 0, 1, 2)
        self.linksThresholdLabel = QtWidgets.QLabel(VerificationSettingsDialog)
        self.linksThresholdLabel.setObjectName("linksThresholdLabel")
        self.gridLayout.addWidget(self.linksThresholdLabel, 3, 0, 1, 1)

        self.retranslateUi(VerificationSettingsDialog)
        self.closeButtonBox.accepted.connect(VerificationSettingsDialog.accept)
        self.closeButtonBox.rejected.connect(VerificationSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(VerificationSettingsDialog)

    def retranslateUi(self, VerificationSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        VerificationSettingsDialog.setWindowTitle(_translate("VerificationSettingsDialog", "Layer Verification Settings"))
        self.axialThresholdLabel.setText(_translate("VerificationSettingsDialog", "Axial crossing threshold (m)"))
        self.axialMinimumLabel.setText(_translate("VerificationSettingsDialog", "Minimum axial length (m)"))
        self.unlinksThresholdLabel.setText(_translate("VerificationSettingsDialog", "Unlinks crossing threshold (m)"))
        self.linksThresholdLabel.setText(_translate("VerificationSettingsDialog", "Links touch threshold (m)"))
